title: Your awesome title
author: jfeng
email: jfeng868@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Quick brown fox jumps over the lazy dog

# site theme
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
